name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: input
    id: shell
    attributes:
      label: Shell
      description: "e.g. zsh 5.9, bash 5.2, fish 3.7"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: "e.g. macOS 15.2, Ubuntu 24.04"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      description: "Output of `node -v`"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: "Paste output from `ambient logs -n 20` or `r status --json`"
      render: shell
