name: Feature Request
description: Suggest an improvement or new capability
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What are you trying to do? Why is it hard today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought about.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Shell integration
        - Memory system
        - Agent support
        - CLI / UX
        - MCP tools
        - Privacy / security
        - Documentation
        - Other
    validations:
      required: true
